version: "3.1"

services:
  db:
    image: postgres:12
    restart: always
    container_name: ficticius-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: brasil
      POSTGRES_PASSWORD: postgres
    ports:
      - "55455:5432"
    networks:
      - backend
    volumes:
      - db-server:/var/lib/postgresql/12/data

  ficticius-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ficticius_app
    restart: always
    depends_on:
      - db
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/brasil
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "9098:9090"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
  payment:
    driver: overlay

volumes:
  db-server: